apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-rc
spec:
  replicas: 3
  template:
    metadata:
     name: helloworld-pod
     labels:
       run: app-helloworld
    spec:
      containers:
      - name: helloworld-container
        image: yadavpk/helloworld:1.0.1
        ports:
        - containerPort: 8080
    
