#CLI command to create helloworld-deployment.yaml
#kubectl create deployment auto-scale --image=yadavpk/helloworld:1.0.1 --port=8080  --dry-run=client -o yaml >helloworld-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloworld-deployment
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld-deployment
    spec:
      containers:
      - image: yadavpk/helloworld:1.0.1
        name: helloworld
        ports:
        - containerPort: 8080
        resources: {}
status: {}

