apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    env: Dev
    apiVersion: 1.0.1    
spec: 
  containers:
  - name: helloworld-container
    image: yadavpk/helloworld
    ports: 
    - containersPort: 8080
